### ISSUE TITLE
The generation of file dose not work using Dart 2.19

### ISSUE THREAD

**Issue by Vildnex** [gmpassos/reflection_factory#27]
I am trying to fallow the main example with the steps below but I don't have any files generated what so ever...

1. creating my main.dart file:
```
import 'package:reflection_factory/reflection_factory.dart';
// Add a reference to the code generated by:
// $> dart run build_runner build
// part 'main.reflection.g.dart';

// Indicates that reflection for class `User` will be generated/enabled:
@EnableReflection()
class User {
  String? email;

  String pass;

  User(this.email, this.pass);

  User.empty() : this(null,'') ;

  bool get hasEmail => email != null;

  bool checkPassword(String pass) {
    return this.pass == pass;
  }
}

void main() {
  var user = User('joe@mail.com', '123');

  // The generated reflection:
  var userReflection = user.reflection;

  var fieldEmail = userReflection.field('email')!;
  print('email: ${fieldEmail.get()}');

  var methodCheckPassword = userReflection.method('checkPassword')!;

  var passOk1 = methodCheckPassword.invoke(['wrong']); // false
  print('pass("wrong"): $passOk1');

  var passOk2 = methodCheckPassword.invoke(['123']); // true
  print('pass("123"): $passOk2');

  // Using the generated `toJson` extension method:
  print('User JSON:');
  print(user.toJson());

  // Using the generated `toJsonEncoded` extension method:
  print('User JSON encoded:');
  print(user.toJsonEncoded());

  // Accessing reflection through class:
  var userReflection2 = User$reflection();

  // Creating an `User` instance from default or empty constructor:
  var user2 = userReflection2.createInstance()!;

  user2.email = 'smith@mail.com';
  user2.pass = 'abc';

  print('User 2 JSON:');
  print(user2.toJson());

}
```
2. adding dependencies in pubspec.yaml:
```
name: advertisement_app
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  reflection_factory: 2.1.0

dev_dependencies:
  build_runner: 2.3.3

```
3. making a build.yaml file:
```
targets:
  $default:
    builders:
      reflection_factory:
        options:
          verbose: true
          sequential: true
          timeout: 2 sec

```
4. running `dart run build_runner build` and I get the following output:
```
Resolving dependencies in /home/vlad/IdeaProjects/TEST_REFLECTION... (1.9s)
  _fe_analyzer_shared 58.0.0 (59.0.0 available)
  analyzer 5.10.0 (5.11.1 available)
  build_daemon 3.1.1 (4.0.0 available)
  build_runner 2.3.3 (2.4.1 available)
  test_api 0.5.1 (0.5.2 available)
Got dependencies in /home/vlad/IdeaProjects/TEST_REFLECTION!
Building package executable... (9.7s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 482ms
[INFO] Precompiling build script... completed, took 8.3s
[INFO] Builder:

  ReflectionBuilder[2.1.0]:
    -- verbose: true
    -- sequential: true
    -- buildStepTimeout: 2 sec

[INFO] Building new asset graph completed, took 1.1s
[INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
[INFO] Running build completed, took 3ms
[INFO] Caching finalized dependency graph completed, took 29ms
[INFO] Succeeded after 40ms with 0 outputs (0 actions)
```

Whatever I am trying to do... I will always get 0 outputs file, does anyone know why?

My project structure:
```
.
├── build.yaml
├── pubspec.lock
├── pubspec.yaml
├── test_main_dir
│   └── main.dart
└── TEST_REFLECTION.iml

1 directory, 5 files
```

**Dart SDK version:** 2.19.6 (stable) (Unknown timestamp) on "linux_x64"

Also, if is for any help this is the `build.dart` from `.dart/build/entrypoint`

```
// ignore_for_file: directives_ordering
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:build_runner_core/build_runner_core.dart' as _i1;
import 'package:reflection_factory/builder.dart' as _i2;
import 'dart:isolate' as _i3;
import 'package:build_runner/build_runner.dart' as _i4;
import 'dart:io' as _i5;

final _builders = <_i1.BuilderApplication>[
  _i1.apply(
    r'reflection_factory:reflection_factory',
    [_i2.reflectionFactory],
    _i1.toDependentsOf(r'reflection_factory'),
    hideOutput: false,
  )
];
void main(
  List<String> args, [
  _i3.SendPort? sendPort,
]) async {
  var result = await _i4.run(
    args,
    _builders,
  );
  sendPort?.send(result);
  _i5.exitCode = result;
}

```

**Comment by gmpassos** [comment]
- You don't need a `build.yaml` file for the `reflection_factory` builder

- You need to uncomment the `part` line:
  `part 'main.reflection.g.dart';`

- The package is being used with Dart 2.19+

If you still have any issue let me know.

Best regards.

**Comment by gmpassos** [comment]
By default it will look for these directories for code to generate:

```
targets:
  $default:
    builders:
      reflection_factory:
        generate_for:
          - bin/*
          - example/*
          - lib/**
          - test/**
```
